### ISSUE TITLE
Micro&etcd似乎无法运行example

### ISSUE THREAD

**Issue by initiali** [hb-go/micro#1]
down下来以后 修改了要导入的etcdv3插件 依旧提示 No private IP address found, and exp
licit IP not provided

**Comment by hb-chen** [comment]
v3我没有装，用etcd测试是可以的
要使用etcd插件，首先要自己编辑micro增加etcd插件
go build -i -o micro-etcd ./main.go ./plugins.go

运行micro
micro-etcd --registry=etcd --registry_address=http://127.0.0.1:2379 api
micro-etcd --registry=etcd --registry_address=http://127.0.0.1:2379 web

运行相关服务
go run main.go plugins.go --registry=etcd --registry_address=http://127.0.0.1:2379
go run main.go plugins.go --registry=etcd --registry_address=http://127.0.0.1:2379
go run main.go plugins.go --registry=etcd --registry_address=http://127.0.0.1:2379
