### ISSUE TITLE
有没有统一的鉴权拦截器

### ISSUE THREAD

**Issue by tttlkkkl** [hb-go/micro#4]
显然 micro api 入口点的UIR和服务的映射做的很好，但是有没有办法做一个统一的拦截器，实现统一的登录鉴权呢。我测试不管如何 `/rpc` 方式都能直接访问后端服务, 这意味着我如果要使用 api 入口点的话就需要在每一个能被发现并请求的服务节点添加登录鉴权，重复劳动甚至是重复鉴权。老兄有没有什么好的解决办法。

**Comment by hb-chen** [comment]
可以看下micro.WrapHandler，做一个统一的鉴权srv，然后在所有的api服务加这个handler wrap

**Comment by sshtest** [comment]
如果用rpc实现的api服务可以通过micro.WrapHandler添加统一的登陆鉴权，但是就本例中echo框架实现的web服务，没有找到添加micro.WrapHandler相关的方法。能否请教下这种情况如何添加？谢谢！
