### ISSUE TITLE
http: proxy error: invalid URL port "42173:0"

### ISSUE THREAD

**Issue by ant8090** [hb-go/micro#5]
下载account/web源码，构建成account-web镜像，然后在Kubernetes部署，访问时报http: proxy error: invalid URL port "42173:0"，请问这是什么原因，构建镜像时有什么特殊配置吗？

**Comment by hb-chen** [comment]
源码编译需要注意go-micro版本兼容问题，k8s示例打包的镜像是go-micro 1.5.0版本
